### ISSUE TITLE
Why are optional parameters not allowed

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [skoshy/eslint-plugin-immer-reducer#1]
Hi

Your plugin checks for two things: Default parameters and optional parameters. In your documentation you are linking to [immer-reducer](https://github.com/esamattis/immer-reducer#-integrating-with-the-redux-ecosystem) which states the following about why default parameters are a bad idea:

>Warning: Due to how immer-reducers action generation works, adding default parameters to the methods will NOT pass it to the action payload, which can make your reducer impure and the values will not be available in middlewares.

However, I don't see any explanation of why optional parameters should not be allowed. Or maybe I'm missing something in above explanation?

Can you please explain and maybe add something about it to the documentation?

Best regards
Jens

**Comment by skoshy** [comment]
Hey Jens, I haven't used this plugin in a while so I'm not entirely sure why :/ Feel free to make a PR to separate out the ESLint rules to one for optional params and one for default params and I'll merge it in and up the major version!

**Comment by jenskuhrjorgensen** [comment]
Hi @skoshy

I'll considered doing that if I get the time. For now we removed the plugin. Thanks for your response. :)
